services:
  web:
    image: php:apache
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: main
      MYSQL_PASSWORD: 138577
      MYSQL_DATABASE: mainDatabase
      MYSQL_PORT: 3306
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground && zip && unzip"

  db:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: 138577
      MYSQL_USER: main
      MYSQL_PASSWORD: 138577
      MYSQL_DATABASE: mainDatabase
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db: